config/routes.rb
SmwSmw::Application.routes.draw do

  root :to => 'home#index'

  get 'home/:id' => 'home#admin'

  get 'admin_edit_listing/:id' => 'listings#admin_edit'

  get 'listings_admin/:id' => 'listings#admin'

  get 'login' => 'user_sessions#new', :as => :login

  get 'logout' => 'user_sessions#destroy', :as => :logout

  get 'searchautos' => 'autolistings#searchautos', :as => :searchautos
  get 'searchmotos' => 'motolistings#searchmotos', :as => :searchmotos
  get 'searchmarine' => 'marinelistings#searchmarine', :as => :searchmarine
  get 'searchpower' => 'powerlistings#searchpower', :as => :searchpower

  get 'about' => 'home#about', :as => :about

  get 'contact' => 'home#contact', :as => :contact

  get 'faq' => 'home#faq', :as => :faq

  get 'whatiwant' => 'whatiwant#whatiwant', :as => :whatiwant

  resources :whatiwant do
    collection do
      get 'get_automodels'
      get 'get_marinesubcategories'
      get 'get_powersubcategories'
    end
  end

  get 'basicsearch' => 'listings#basicsearch', :as => :basicsearch

  get 'newmain' => 'listings#newmain', :as => :newmain

  get 'photos/:id' => 'photos#showlarge', :as => :largephoto

  get 'medphoto/:id' => 'photos#showmedium', :as => :medphoto

  get 'smallphoto/:id' => 'photos#showsmall', :as => :smallphoto

  get 'inbox' => 'messages#inbox', :as => :inbox

  get 'sent' => 'messages#sent', :as => :sent

  resources :messages do
    member do
      delete 'deletesent'
      get 'reply'
      post 'create_reply'
    end
  end

  get 'privacypolicy' => 'home#privacypolicy', :as => :privacypolicy

  get 'visitoragreement' => 'home#visitoragreement', :as => :visitoragreement

   resources :wishlists do
     collection do
       get 'new_auto'
       get 'new_moto'
       get 'new_marine'
       get 'new_power'
     end
   end

   resources :favorites
   resources :users, :has_many=>:listings

   resources :users do
     resources :listings do

     end
   end

   resources :listings do
    resources :photos
   end

   resources :user_sessions

   resources :users, :shallow => true do
    resources :listings, :name_prefix => nil do
      resources :photos
    end
    resources :wishlists
    resources :favorites
  end

   resources :password_resets
   resources :autocategories
   resources :automodels
   resources :marinecategories do
     collection do
       get 'get_marinesubcategories'
     end
   end
   resources :marinemakes
   resources :motocategories
   resources :motomakes
   resources :powercategories do
     collection do
       get 'get_powersubcategories'
     end
   end
   resources :powermakes
   resources :autolistings do
     collection do
       post 'autolistingsresults'
       get 'get_automodels'
       post 'autolistingsresults_new'
       get 'autolistingsresults_new'
     end
   end

   resources :motolistings do
     collection do
       post 'motolistingsresults'
       get 'motolistingsresults'
     end
   end

   resources :marinelistings do
     collection do
       post 'marinelistingsresults'
       get 'marinelistingsresults'
     end
   end

   resources :powerlistings do
     collection do
       post 'powerlistingsresults'
       get 'powerlistingsresults'
     end
   end

end

app/models/message.rb
class Message < ActiveRecord::Base

  attr_accessible :recipient_id, :name, :email, :phone, :subject, :body, :sender_id, :listing_id

	validates :recipient_id, :subject, :body, :presence => true
	belongs_to :sender, :class_name => "User", :foreign_key => "sender_id"
	belongs_to :recipient, :class_name => "User", :foreign_key => "recipient_id"
	belongs_to :listing
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  layout 'application'
  def inbox
    @messages = current_user.received_messages.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @messages }
    end
  end

  def sent
    @messages = current_user.sent_messages.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.xml
  def show
  	if current_user
  		@message = Message.find(params[:id])
		  if current_user.id == @message.sender_id or current_user.id == @message.recipient_id
			  @message.read_at = Time.now
			  @message.save
			else
				not_authorized = true
		  end
		else
			not_authorized = true
		end

    respond_to do |format|
    	if not_authorized == true
    		flash[:notice] = 'You are not authorized to view that message.'
    		format.html {redirect_to root_url}
    	else
	      format.html # show.html.erb
  	    format.xml  { render :xml => @message }
  	  end
    end
  end

  # GET /messages/new
  # GET /messages/new.xml
  def new
    @message = Message.new
    @sender = current_user

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @message }
    end
  end
  
	def reply
    puts "------------------------------"
    puts params.inspect
    @original_message = Message.find(params[:id])
    @message = Message.new
		@sender = current_user
		
    respond_to do |format|
      format.html 
      format.xml  { render :xml => @message }
    end
  end
  
  # POST /messages
  # POST /messages.xml
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        flash[:notice] = 'Message was successfully sent.'
        format.html { redirect_to :back }
        format.xml  { render :xml => @message, :status => :created, :location => @message }
      else
      	flash[:notice] = 'Message was not sent.  Please check required fields.'
      	format.html { redirect_to :back }
        #format.html { render :action => "new" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

	def create_reply
    @reply_to_message = Message.find(params[:id])
    @message = Message.new(params[:message])

    @message.body = @reply_to_message.body
    @message.recipient_id = @reply_to_message.recipient_id

    respond_to do |format|
      if @message.save!
        flash[:notice] = 'Reply Message was successfully sent.'
        format.html { redirect_to sent_url }
        format.xml  { render :xml => @message, :status => :created, :location => @message }
      else
      	flash[:notice] = 'Reply Message was not sent.  Please check required fields.'
      	format.html { redirect_to :back }
				format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end


  def destroy
    if params[:inbox] == "1"
    	@message = current_user.received_messages.find(params[:id])
    	@message.update_attribute("recipient_deleted_at", Time.now)
    	flash[:notice] = 'Message was successfully deleted.'
    	redirect_to inbox_url
    elsif params[:sent] == "1"
	    @message = current_user.sent_messages.find(params[:id])
    	@message.update_attribute("sender_deleted_at", Time.now)
    	flash[:notice] = 'Message was successfully deleted.'
    	redirect_to sent_url
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_show_admin.html.erb
<tr>
  <td width="8%" valign="top"><p>From:</p></td>
  <td width="92%">
  	<p><%=h @message.name %></p>
  	<p><%=h @message.email %></p>
  </td>
</tr>
<tr>
  <td valign="top"><p>Date:</p></td>
  <td><p><%=h @message.created_at %></p></td>
</tr>
<tr>
  <td valign="top"><p>Phone:</p></td>
  <td><p><%=h @message.phone %></p></td>
</tr>
<tr>
  <td valign="top"><p>Subject:</p></td>
  <td><p><%=h @message.subject %></p></td>
</tr>
<tr>
  <td valign="top"><p>Message:</p></td>
  <td><p><%=h @message.body %></p></td>
</tr>


app/views/messages/_show_normal.html.erb
<tr>
  <td width="8%" valign="top"><p>From:</p></td>
  <td width="92%"><p><%=h @message.sender.username %></p></td>
</tr>
<tr>
  <td valign="top"><p>Date:</p></td>
  <td><p><%=h @message.created_at %></p></td>
</tr>
<tr>
  <td valign="top" class="formText"><p>Listing:</p></td>
  <td>
  	<% if @message.listing %>
  		<p><%=h @message.listing.year %> <%=h @message.listing.make %> <%=h @message.listing.model %></p>
  	<% else %>
  		<p>Listing has been removed or cannot be found.</p>
  	<% end %>
  </td>
</tr>
<tr>
  <td valign="top" class="formText"><p>Subject:</p></td>
  <td><p><%=h @message.subject %></p></td>
</tr>
<tr>
  <td valign="top" class="formText"><p>Message:</p></td>
  <td><p><%=h @message.body %></p></td>
</tr>

app/views/messages/inbox.html.erb
<div id="content">
<div class="page"> <img class="p_img" src="/assets/fullwidth.jpg" width="1050" />
  <div class="leftcontent">
    <div class="uppercontent"> <span>Mailbox</span>
      <div class="buttons">
        <style>
            .black_overlay{
                display: none;
                position: absolute;
                top: 0%;
                left: 0%;
                width: 100%;
                height: 100%;
                background-color: black;
                z-index:1001;
                -moz-opacity: 0.8;
                opacity:.80;
                filter: alpha(opacity=80);
                position:fixed;
            }
            .white_content {
                background-color: #FFFFFF;
                display: none;
                height: auto;
                left: 25%;
                position: fixed;
                top: 25%;
                width: 50%;
                z-index: 1002;
                /*padding: 16px;*/
                /*border: 16px solid #fff;*/

            }
            .white_content a {
                background-image: url("close.png");
                background-repeat: no-repeat;
                height: 38px;
                position: absolute;
                right: -19px;
                top: -24px;
                width: 39px;
                z-index: 999999;
            }


            .white_content .innerpart .inner2part {
                padding:30px;
            }
        </style>
        <div id="light" class="white_content">
          <div class="innerpart">
            <div class="inner2part">
              <p class="fc">To:</p>
              <p class="sc">Sample Member</p>
              <p class="ssubject">Subject:</p>
              <p class="sc">RE: 2006 Corvette</p>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
              <hr style=" border-top:4px dotted #AAAAAA" />
              <div>From: Sample Member</div>
              <div>To: Sample Recipient</div>
              <div>Date: Saturday, July 13, 2013 at 4:15pm</div>
              <div>Subject: 2006 Corvette</div>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt. mollit anim id est laborum. </p>
              <form action="#">
                <input type="submit" value="Send" />
              </form>
              <div class="clear"></div>
            </div>
          </div>
          <a style=" color:#000" href = "javascript:void(0)" onclick = "document.getElementById('light').style.display='none';document.getElementById('fade').style.display='none'"></a></div>
        <div id="fade" class="black_overlay"></div>
      </div>
      <div>
        <!-- panel -->

        <!-- panel -->
      </div>
      <div class="clear"></div>
    </div>
    <div class="mainpannel">
      <table width="883" border="0" cellpadding="20" cellspacing="0">
        <% if flash[:notice] %>
            <div class="notice"><%= flash[:notice] %></div>
        <% end %>
        <tr>
          <td align="left" valign="top">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td>
                  <span class="formText">
							<%= link_to "Inbox", inbox_url, {:style=>'color:#649D4A'} %>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <%= link_to "Sent", sent_url, {:style=>'color:#649D4A'} %>
							<br />
						</span>
                </td>
              </tr>
              <tr>
                <td>
                  <table width="100%" border="0" cellpadding="0" cellspacing="0">
                    <tr class="messageBar">
                      <th height="26"><p>Received</p></td>
                      <th height="26"><p>Sender</p></td>
                      <th height="26"><p>Listing</p></td>
                      <th height="26"><p>Read</p></td>
                      <th height="26"><p>Subject</p></td>
                    </tr>

                    <% @messages.each do |message| %>
                        <tr>
                          <td><p><%=h message.created_at %></p></td>
                          <td>
                            <% if message.sender %>
                                <p><%=h message.sender.username %></p>
                            <% else %>
                                <p><%=h message.name %></p>
                            <% end %>
                          <td>
                            <% if message.listing %>
                                <% if message.listing.model.blank? %>
                                    <%= link_to message.listing.year.to_s + " " + message.listing.make, message.listing, {:style=>'color:#649D4A'} %>
                                <% else %>
                                    <%= link_to message.listing.year.to_s + " " + message.listing.make + " " + message.listing.model, message.listing, {:style=>'color:#649D4A'} %>
                                <% end %>
                            <% end %>
                          </td>
                          <td><p><%=h message.read_at %></p></td>
                          <td><b><%= link_to message.subject, message, {:style=>'color:#649D4A'} %><b></td>
                          <td><%= link_to "Delete", message_path(message, :inbox => "1"), {:method => :delete,:style=>'color:#649D4A'} %></td>
                        </tr>
                    <% end %>

                  </table>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>

    <div class="clear"></div>
    </div>
    <script type="text/javascript">
        <!--
        var TabbedPanels1 = new Spry.Widget.TabbedPanels("TabbedPanels1");
        var TabbedPanels2 = new Spry.Widget.TabbedPanels("TabbedPanels2");
        //-->
    </script>
  </div>
  <div class="clear"></div>
</div>
</div>














>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= form_for(@message) do |f| %>
    <% if @message.errors.any? %>
        <div id="errorExplanation">
          <h2><%= pluralize(@message.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% @message.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

  <p>
    <%= f.hidden_field :sender_id, :value => @sender.id %>
  </p>
  <p>
    <%= f.label :recipient_id %><br />
    <%= f.text_field :recipient_id, :readonly => :true, :value => '1' %>
  </p>
  <p>
    <%= f.label :listing_id %><br />
    <%= f.text_field :listing_id %>
  </p>
  <p>
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', messages_path %>

app/views/messages/sent.html.erb
<div id="content">
  <div class="page"> <img class="p_img" src="/assets/fullwidth.jpg" width="1050" />
    <div class="leftcontent">
      <div class="uppercontent"> <span>Mailbox</span>
        <div class="buttons">
          <style>
              .black_overlay{
                  display: none;
                  position: absolute;
                  top: 0%;
                  left: 0%;
                  width: 100%;
                  height: 100%;
                  background-color: black;
                  z-index:1001;
                  -moz-opacity: 0.8;
                  opacity:.80;
                  filter: alpha(opacity=80);
                  position:fixed;
              }
              .white_content {
                  background-color: #FFFFFF;
                  display: none;
                  height: auto;
                  left: 25%;
                  position: fixed;
                  top: 25%;
                  width: 50%;
                  z-index: 1002;
                  /*padding: 16px;*/
                  /*border: 16px solid #fff;*/

              }
              .white_content a {
                  background-image: url("close.png");
                  background-repeat: no-repeat;
                  height: 38px;
                  position: absolute;
                  right: -19px;
                  top: -24px;
                  width: 39px;
                  z-index: 999999;
              }


              .white_content .innerpart .inner2part {
                  padding:30px;
              }
          </style>
          <div id="light" class="white_content">
            <div class="innerpart">
              <div class="inner2part">
                <p class="fc">To:</p>
                <p class="sc">Sample Member</p>
                <p class="ssubject">Subject:</p>
                <p class="sc">RE: 2006 Corvette</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
                <hr style=" border-top:4px dotted #AAAAAA" />
                <div>From: Sample Member</div>
                <div>To: Sample Recipient</div>
                <div>Date: Saturday, July 13, 2013 at 4:15pm</div>
                <div>Subject: 2006 Corvette</div>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt. mollit anim id est laborum. </p>
                <form action="#">
                  <input type="submit" value="Send" />
                </form>
                <div class="clear"></div>
              </div>
            </div>
            <a style=" color:#000" href = "javascript:void(0)" onclick = "document.getElementById('light').style.display='none';document.getElementById('fade').style.display='none'"></a></div>
          <div id="fade" class="black_overlay"></div>
        </div>
        <div>
          <!-- panel -->

          <!-- panel -->
        </div>
        <div class="clear"></div>
      </div>
      <div class="mainpannel">
        <table width="883" border="0" cellpadding="20" cellspacing="0">
          <% if flash[:notice] %>
              <div class="notice"><%= flash[:notice] %></div>
          <% end %>
          <tr>
            <td align="left" valign="top">
              <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td>
                    <span class="formText">
							<%= link_to "Inbox", inbox_url, {:style=>'color:#649D4A'} %>
                      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                      <%= link_to "Sent", sent_url, {:style=>'color:#649D4A'} %>
                      <br />
							<br />
						</span>
                  </td>
                </tr>
                <tr>
                  <td>
                    <table width="100%" border="0" cellpadding="0" cellspacing="0">
                      <tr class="messageBar">
                        <th height="26"><p>Sent</p></td>
                        <th height="26"><p>Recipient</p></td>
                        <th height="26"><p>Listing</p></td>
                        <th height="26"><p>Read</p></td>
                        <th height="26"><p>Subject</p></td>
                      </tr>

                      <% @messages.each do |message| %>
                          <tr>
                            <td><p><%=h message.created_at %></p></td>
                            <td><p><%=h message.recipient.username %></p></td>
                            <td>
                              <% if message.listing %>
                                  <% if message.listing.model.blank? %>
                                      <%= link_to message.listing.year.to_s + " " + message.listing.make, message.listing, {:style=>'color:#649D4A'}%>
                                  <% else %>
                                      <%= link_to message.listing.year.to_s + " " + message.listing.make + " " + message.listing.model, message.listing , {:style=>'color:#649D4A'}%>
                                  <% end %>
                              <% end %>
                            </td>
                            <td><p><%=h message.read_at %></p></td>
                            <td><b><%= link_to message.subject, message, {:style=>'color:#649D4A'} %></b></td>
                            <td><p><%= link_to "Delete", message_path(message, :inbox => "1"), {:method => :delete,:style=>'color:#649D4A'} %></p></td>
                          </tr>
                      <% end %>

                    </table>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>

        <div class="clear"></div>
      </div>
      <script type="text/javascript">
          <!--
          var TabbedPanels1 = new Spry.Widget.TabbedPanels("TabbedPanels1");
          var TabbedPanels2 = new Spry.Widget.TabbedPanels("TabbedPanels2");
          //-->
      </script>
    </div>
    <div class="clear"></div>
  </div>
</div>

app/views/messages/show.html.erb
<div id="content">
  <div class="page"> <img class="p_img" src="/assets/fullwidth.jpg" width="1050" />
    <div class="leftcontent">
      <div class="uppercontent"> <span>Mailbox</span>
        <div class="buttons">
          <style>
              .black_overlay{
                  display: none;
                  position: absolute;
                  top: 0%;
                  left: 0%;
                  width: 100%;
                  height: 100%;
                  background-color: black;
                  z-index:1001;
                  -moz-opacity: 0.8;
                  opacity:.80;
                  filter: alpha(opacity=80);
                  position:fixed;
              }
              .white_content {
                  background-color: #FFFFFF;
                  display: none;
                  height: auto;
                  left: 25%;
                  position: fixed;
                  top: 25%;
                  width: 50%;
                  z-index: 1002;
                  /*padding: 16px;*/
                  /*border: 16px solid #fff;*/

              }
              .white_content a {
                  background-image: url("close.png");
                  background-repeat: no-repeat;
                  height: 38px;
                  position: absolute;
                  right: -19px;
                  top: -24px;
                  width: 39px;
                  z-index: 999999;
              }


              .white_content .innerpart .inner2part {
                  padding:30px;
              }
          </style>
          <div id="light" class="white_content">
            <div class="innerpart">
              <div class="inner2part">
                <p class="fc">To:</p>
                <p class="sc">Sample Member</p>
                <p class="ssubject">Subject:</p>
                <p class="sc">RE: 2006 Corvette</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
                <hr style=" border-top:4px dotted #AAAAAA" />
                <div>From: Sample Member</div>
                <div>To: Sample Recipient</div>
                <div>Date: Saturday, July 13, 2013 at 4:15pm</div>
                <div>Subject: 2006 Corvette</div>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt. mollit anim id est laborum. </p>
                <form action="#">
                  <input type="submit" value="Send" />
                </form>
                <div class="clear"></div>
              </div>
            </div>
            <a style=" color:#000" href = "javascript:void(0)" onclick = "document.getElementById('light').style.display='none';document.getElementById('fade').style.display='none'"></a></div>
          <div id="fade" class="black_overlay"></div>
        </div>
        <div>
          <!-- panel -->

          <!-- panel -->
        </div>
        <div class="clear"></div>
      </div>
      <div class="mainpannel">
        <table width="883" border="0" cellpadding="20" cellspacing="0">
          <tr>
            <td align="left" valign="top">
              <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td>

                    <span class="formText">
							<%= link_to "Inbox", inbox_url, {:style=>'color:#649D4A'}  %>
                      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                      <%= link_to "Sent", sent_url, {:style=>'color:#649D4A'}  %>
                      <br />
							<br />
						</span>
                  </td>
                </tr>
              </table>
              <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td>
                    <table width="100%" border="0" cellpadding="3" cellspacing="3" class="emailMessage" id="messageContent">
                      <% if @message.sender %>
                          <%= render :partial => 'show_normal' %>
                      <% else %>
                          <%= render :partial => 'show_admin' %>
                      <% end %>
                    </table>
                  </td>
                </tr>
                <tr>
                  <td class="messageBar">
                    <table width="100%" border="0" cellpadding="0" cellspacing="0" id="messageCategories">
                      <tr>
                        <td width="25%" height="26" align="right">
                          <%= form_for @message, :url => {:controller => "messages", :action => "reply"} do |f| %>

                              <%= f.hidden_field :id, :value => @message.id %>
                              <%= f.hidden_field :recipient_id, :value => @message.sender_id %>
                              <%= f.hidden_field :listing_id, :value => @message.listing_id %>
                              <%= f.hidden_field :subject, :value => "RE: " + @message.subject %>
                              <p><%= link_to 'Reply',  reply_message_path(@message), :style=>'color:#649D4A'%> | <%= link_to "Delete", message_path(@message), :class => "messageBar", :confirm => "Are you sure you want to delete this message?", :method => :delete, :style=>'color:#649D4A' %></p>
                          <% end %>
                        </td>
                        <td width="20%" height="26">&nbsp;</td>
                        <td height="26">&nbsp;</td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>
          </tr>
          </td>
        </table>

        <div class="clear"></div>
      </div>
      <script type="text/javascript">
          <!--
          var TabbedPanels1 = new Spry.Widget.TabbedPanels("TabbedPanels1");
          var TabbedPanels2 = new Spry.Widget.TabbedPanels("TabbedPanels2");
          //-->
      </script>
    </div>
    <div class="clear"></div>
  </div>
</div>