config/routes.rb
SmwSmw::Application.routes.draw do

  root :to => 'home#index'

  get 'home/:id' => 'home#admin'

  get 'admin_edit_listing/:id' => 'listings#admin_edit'

  get 'listings_admin/:id' => 'listings#admin'

  get 'login' => 'user_sessions#new', :as => :login

  get 'logout' => 'user_sessions#destroy', :as => :logout

  get 'searchautos' => 'autolistings#searchautos', :as => :searchautos
  get 'searchmotos' => 'motolistings#searchmotos', :as => :searchmotos
  get 'searchmarine' => 'marinelistings#searchmarine', :as => :searchmarine
  get 'searchpower' => 'powerlistings#searchpower', :as => :searchpower

  get 'about' => 'home#about', :as => :about

  get 'contact' => 'home#contact', :as => :contact

  get 'faq' => 'home#faq', :as => :faq

  get 'whatiwant' => 'whatiwant#whatiwant', :as => :whatiwant

  resources :whatiwant do
    collection do
      get 'get_automodels'
      get 'get_marinesubcategories'
      get 'get_powersubcategories'
    end
  end

  get 'basicsearch' => 'listings#basicsearch', :as => :basicsearch

  get 'newmain' => 'listings#newmain', :as => :newmain

  get 'photos/:id' => 'photos#showlarge', :as => :largephoto

  get 'medphoto/:id' => 'photos#showmedium', :as => :medphoto

  get 'smallphoto/:id' => 'photos#showsmall', :as => :smallphoto

  get 'inbox' => 'messages#inbox', :as => :inbox

  get 'sent' => 'messages#sent', :as => :sent

  resources :messages do
    member do
      delete 'deletesent'
      get 'reply'
      post 'create_reply'
    end
  end

  get 'privacypolicy' => 'home#privacypolicy', :as => :privacypolicy

  get 'visitoragreement' => 'home#visitoragreement', :as => :visitoragreement

   resources :wishlists do
     collection do
       get 'new_auto'
       get 'new_moto'
       get 'new_marine'
       get 'new_power'
     end
   end

   resources :favorites
   resources :users, :has_many=>:listings

   resources :users do
     resources :listings do

     end
   end

   resources :listings do
    resources :photos
   end

   resources :user_sessions

   resources :users, :shallow => true do
    resources :listings, :name_prefix => nil do
      resources :photos
    end
    resources :wishlists
    resources :favorites
  end

   resources :password_resets
   resources :autocategories
   resources :automodels
   resources :marinecategories do
     collection do
       get 'get_marinesubcategories'
     end
   end
   resources :marinemakes
   resources :motocategories
   resources :motomakes
   resources :powercategories do
     collection do
       get 'get_powersubcategories'
     end
   end
   resources :powermakes
   resources :autolistings do
     collection do
       post 'autolistingsresults'
       get 'get_automodels'
       post 'autolistingsresults_new'
       get 'autolistingsresults_new'
     end
   end

   resources :motolistings do
     collection do
       post 'motolistingsresults'
       get 'motolistingsresults'
     end
   end

   resources :marinelistings do
     collection do
       post 'marinelistingsresults'
       get 'marinelistingsresults'
     end
   end

   resources :powerlistings do
     collection do
       post 'powerlistingsresults'
       get 'powerlistingsresults'
     end
   end

end

app/models/listing.rb
class Listing < ActiveRecord::Base

  attr_accessible :listingtype, :expired_at, :year, :mileage, :make, :vin, :model, :price, :body, :desc, :exterior_color,
                  :interior_color, :doors, :engine, :transmission, :drive, :fuel, :category, :subcategory, :length, :hull

  STATES = ['AK','AL','AR','AZ','CA','CO','CT','DE','FL','GA','HI','IA','ID','IL','IN','KS','KY','LA','MA','MD','ME','MI',
            'MN','MO','MS','MT','NC','ND','NE','NH','NJ','NM','NV','NY','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VA',
            'VT','WA','WI','WV','WY']

	validates :listingtype, :presence => true

	validates :price, :mileage, :numericality =>
                    { :only_integer => true,
                      :message => "is not a number or contains extra characters.  Please use only numbers.",
                      :allow_nil => true
                    }
	belongs_to :users
	belongs_to :owner, :class_name => "User", :foreign_key => "user_id"
	has_many :messages
	has_many :photos, :dependent => :destroy
	has_many :wishlists, :foreign_key => "user_id", :primary_key => "user_id"
#will_paginate stuff
	cattr_reader :per_page
  @@per_page = 50

	#default_scope :conditions => ["expired_at >= ?", Date.today]

  def self.search_m(params)
   Listing.where("make = ? AND model = ? AND category = ? price = ?", params[:make], params[:model], params[:category], )
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

	def admin
		
		respond_to do |format|
			@user = current_user
			if @user
				if @user.admin
					page = params[:page] || 1
					@listings = Listing.paginate :page => params[:page], :order => 'created_at DESC'
					@listings_count = @listings.count
			    format.html # admin.html.erb
			  else
			  	flash[:notice] = 'Restricted Page'
			  	format.html {redirect_to(root_url)}
			  end
		  else
		  	flash[:notice] = 'Restricted Page'
		  	format.html {redirect_to(root_url)}
		  end
		end
  end
	
	def admin_edit
  	@user = current_user
    @listing = Listing.find(params[:id])
		
		if @user
			if @user.admin
			#Admin user is logged in 
				if @listing.listingtype == "auto"
					@automakes = Automodels.find(:all, :order => 'make ASC', :select => 'distinct make')
					@automodels = Automodels.find_all_by_make(@listing.make, :order => "model ASC").map{|m| [m.model, m.model]}
					@autocategories = Autocategories.all
				elsif @listing.listingtype == "moto"
					@motocategories = Motocategories.find(:all, :order => 'category ASC')
					@motomakes = Motomakes.find(:all, :order => 'sort_order ASC')
				elsif @listing.listingtype == "marine"
					@marinecategories = Marinecategories.find(:all, :order => 'category ASC', :select => 'distinct category')
					@marinesubcategories = Marinecategories.find_all_by_category(@listing.category, :order => "subcategory ASC").map{|m| [m.subcategory, m.subcategory]}
					@marinemakes = Marinemakes.find(:all, :order => 'make ASC')
				elsif @listing.listingtype == "power"
					@powercategories = Powercategories.find(:all, :order => 'category ASC', :select => 'distinct category')
					@powersubcategories = Powercategories.find_all_by_category(@listing.category, :order => "subcategory ASC").map{|m| [m.subcategory, m.subcategory]}
					@powermakes = Powermakes.find(:all, :order => 'sort_order ASC')
				else
				#Redirect non-admin user to home page
					respond_to do |format|
						flash[:notice] = 'Restricted Page'
						format.html {redirect_to(root_url)}
					end
				end
		
				@photo = @listing.photos.new(params[:photo])
				@photo_count = @listing.photos.count
			
				render "edit"
			end
		else
		#Redirect non-admin user to home page
			respond_to do |format|
				flash[:notice] = 'Restricted Page'
				format.html {redirect_to(root_url)}
			end
		end
  end
	
	def get_automodels
		@automodels = Automodels.find_all_by_make(params[:make], :order => "model ASC").map{|m| [m.model, m.model]}
		
		render :update do |page|
			page.replace_html('automodelsdiv', :partial => 'automodels_select', :object => @automodels)
		end
	end
	  
	def get_marinesubcategories
		@marinesubcategories = Marinecategories.find_all_by_category(params[:category], :order => "subcategory ASC").map{|m| [m.subcategory, m.subcategory]}
		
		render :update do |page|
			page.replace_html('marinesubcategoriesdiv', :partial => 'marinesubcategories_select', :object => @marinesubcategories)
		end
	end
	
	def get_powersubcategories
		@powersubcategories = Powercategories.find_all_by_category(params[:category], :order => "subcategory ASC").map{|m| [m.subcategory, m.subcategory]}
		
		render :update do |page|
			page.replace_html('powersubcategoriesdiv', :partial => 'powersubcategories_select', :object => @powersubcategories)
		end
	end
	
	def replacebigphoto
		@listing = Listing.find(params[:listing_id])
		@bigphoto = @listing.photos.find(params[:id])
		
		render :update do |page|
			page.replace_html('bigphoto', :partial => 'bigphoto', :object => @bigphoto)
		end
	end
	
  # GET /listings
  # GET /listings.xml
  def index
    if current_user
      @user = current_user
      @listings = @user.listings
      @listings_count = @user.listings.count
    else
      redirect_to new_user_path
    end
  end

  # GET /listings/1
  # GET /listings/1.xml
  def show
    @listing = Listing.find(params[:id])
    if current_user
    	@message = Message.new
    	@favorites = Favorite.new
    end
    @sender = current_user
    @recipient = @listing.owner
    @photo_count = @listing.photos.count

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @listing }
    end
  end
	
	def newmain
		@user = current_user
	end
  # GET /listings/new@automakes = Automodels.find(:all, :order => 'make ASC', :select => 'distinct make')
  # GET /listings/new.xml
  def new
  	if current_user
	  	@user = current_user
	    @listing = @user.listings.new(params[:listing])
	    @automakes = Automodels.find(:all, :order => 'make ASC', :select => 'distinct make')
	    @automodels = ""
	    @autocategories = Autocategories.all
	
	    respond_to do |format|
	      format.html # new.html.erb
	      format.xml  { render :xml => @listing }
	    end
	  else
	  	redirect_to new_user_path
	  end
  end

  # GET /listings/1/edit
  def edit
  	@user = current_user
    @listing = Listing.find(params[:id])
    #@listing = current_user.listings.where("id = ?", params[:id]) #TODO
  	#Stop other users from editing listings that don't belong to them!
  	if @user
			#if @user.id != @listing.user
				#redirect_to @listing
			#else
				#Current user logged in is editing his own listing
				if @listing.listingtype == "auto"
					@automakes = Automodels.find(:all, :order => 'make ASC', :select => 'distinct make')
					@automodels = Automodels.find_all_by_make(@listing.make, :order => "model ASC").map{|m| [m.model, m.model]}
					@autocategories = Autocategories.all
				elsif @listing.listingtype == "moto"
					@motocategories = Motocategories.find(:all, :order => 'category ASC')
					@motomakes = Motomakes.find(:all, :order => 'sort_order ASC')
				elsif @listing.listingtype == "marine"
					@marinecategories = Marinecategories.find(:all, :order => 'category ASC', :select => 'distinct category')
					@marinesubcategories = Marinecategories.find_all_by_category(@listing.category, :order => "subcategory ASC").map{|m| [m.subcategory, m.subcategory]}
					@marinemakes = Marinemakes.find(:all, :order => 'make ASC')
				elsif @listing.listingtype == "power"
					@powercategories = Powercategories.find(:all, :order => 'category ASC', :select => 'distinct category')
					@powersubcategories = Powercategories.find_all_by_category(@listing.category, :order => "subcategory ASC").map{|m| [m.subcategory, m.subcategory]}
					@powermakes = Powermakes.find(:all, :order => 'sort_order ASC')
				end
				
				@photo = @listing.photos.new(params[:photo])
				@photo_count = @listing.photos.count
			#end
		else
			redirect_to @listing
		end
  end

  # POST /listings
  # POST /listings.xml
  def create
		@user = current_user
    @listing = @user.listings.new(params[:listing])

    respond_to do |format|
      if @listing.save
        flash[:notice] = 'Listing was successfully created.'
        format.html { redirect_to edit_user_listing_path(@user, @listing) }
        format.xml  { render :xml => @listing, :status => :created, :location => @listing }
      else
      	flash[:notice] = @listing.errors.full_messages * "<br />"
        format.html { redirect_to :back }
        format.xml  { render :xml => @listing.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /listings/1
  # PUT /listings/1.xml
  def update
    @listing = Listing.find(params[:id])

    respond_to do |format|
      if @listing.update_attributes(params[:listing])
        flash[:notice] = 'Listing was successfully updated.'
        format.html { redirect_to wishlists_path }
        format.xml  { head :ok }
      else
      	flash[:notice] = @listing.errors.full_messages * "<br />"
        format.html { redirect_to :back }
        format.xml  { render :xml => @listing.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.xml
  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy

    respond_to do |format|
    	flash[:notice] = 'Listing was successfully deleted.'
      format.html { redirect_to(:back) }
      format.xml  { head :ok }
    end
  end
  #def recent
  #  @listings = Listing.all(:order => "created_at DESC", :limit => 4)
  #  
	#	render :partial => "recent"
  #end

  private

  def listing_params
    params.require(:listing).permit(:listingtype, :expired_at, :year, :mileage, :make, :vin, :model, :price, :body, :desc, :exterior_color,
                                    :interior_color, :doors, :engine, :transmission, :drive, :fuel, :category, :subcategory, :length, :hull)
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_automodels.html.erb
<%= collection_select :listing, :model, @automodels, :model, :model, {:prompt => "-Select a Make First"} %>

app/views/listings/_bigphoto.html.erb
<%= link_to image_tag(medphoto_path(@bigphoto, :jpg), :alt => @bigphoto.name, :border => 0), largephoto_path(@bigphoto, :jpg) %>

app/views/listings/_marine.html.erb
<% if @listings_count > 0 %>
	<%= @listings_count %> listings found.
		<table class="searchresults" border="1" cellpadding="4">
  		<tr>
  			<th></th>
  			<th><%= remote_order_by_link :year %></th>
  			<th><%= remote_order_by_link :make %></th>
  			<th><%= remote_order_by_link :model %></th>
  			<th><%= remote_order_by_link :price %></th>
  		</tr>
  		<% @listings.each do |listing| %>
	  		<tr>
	  			<td>
	  			<% listing.photos.all(:limit => 1).each do |photo| %>
	  		  	<%= image_tag smallphoto_url(photo, :jpg), :alt => photo.name %></td>
			    <% end %>
			    </td>
			    <td><%=h listing.year %></td>
			    <td><%=h listing.make %></td>
			    <td><%=h listing.model %></td>
			    <td><%=h listing.price %></td>
			    <td><%= link_to 'Show', listing %></td>
			  </tr>
			<% end %>
		</table>
		<br/>
		Per Page: <%= remote_per_page_select %>
		<% if @search.page_count > 1 %>
			<div class="pages">
				<%= remote_page_links %>
			</div>
		<% end %>
<% else %>
	No listings found.
<% end %>

app/views/listings/_motorcycles.html.erb
<% if @listings_count > 0 %>
	<%= @listings_count %> listings found.
		<table class="searchresults" border="1" cellpadding="4">
  		<tr>
  			<th></th>
  			<th><%= remote_order_by_link :year %></th>
  			<th><%= remote_order_by_link :make %></th>
  			<th><%= remote_order_by_link :model %></th>
  			<th><%= remote_order_by_link :price %></th>
  		</tr>
  		<% @listings.each do |listing| %>
	  		<tr>
	  			<td>
	  			<% listing.photos.all(:limit => 1).each do |photo| %>
	  		  	<%= image_tag smallphoto_url(photo, :jpg), :alt => photo.name %></td>
			    <% end %>
			    </td>
			    <td><%=h listing.year %></td>
			    <td><%=h listing.make %></td>
			    <td><%=h listing.model %></td>
			    <td><%=h listing.price %></td>
			    <td><%= link_to 'Show', listing %></td>
			  </tr>
			<% end %>
		</table>
		<br/>
		Per Page: <%= remote_per_page_select %>
		<% if @search.page_count > 1 %>
			<div class="pages">
				<%= remote_page_links %>
			</div>
		<% end %>
<% else %>
	No listings found.
<% end %>

app/views/listings/_mylistings_marine.html.erb
<table width="100%" border="0" align="left" cellpadding="3" cellspacing="3" class="listingDetails" id="listingDetails">
	<tr>
		<td align="left">Year: <%=h listing.year %></td>
	</tr>
	<tr>
		<td align="left">Category: <%=h listing.category %></td>
	</tr>
	<tr>
		<td align="left">Subcategory: <%=h listing.subcategory %></td>
	</tr>
	<tr>
		<td align="left">Make: <%=h listing.make %></td>
	</tr>
	<tr>
		<td align="left">Asking Price: <%=h number_to_currency(listing.price, :precision => 0) %></td>
	</tr>
</table>

app/views/listings/_powersports.html.erb
<% if @listings_count > 0 %>
	<%= @listings_count %> listings found.
		<table class="searchresults" border="1" cellpadding="4">
  		<tr>
  			<th></th>
  			<th><%= remote_order_by_link :year %></th>
  			<th><%= remote_order_by_link :make %></th>
  			<th><%= remote_order_by_link :model %></th>
  			<th><%= remote_order_by_link :price %></th>
  		</tr>
  		<% @listings.each do |listing| %>
	  		<tr>
	  			<td>
	  			<% listing.photos.all(:limit => 1).each do |photo| %>
	  		  	<%= image_tag smallphoto_url(photo, :jpg), :alt => photo.name %></td>
			    <% end %>
			    </td>
			    <td><%=h listing.year %></td>
			    <td><%=h listing.make %></td>
			    <td><%=h listing.model %></td>
			    <td><%=h listing.price %></td>
			    <td><%= link_to 'Show', listing %></td>
			  </tr>
			<% end %>
		</table>
		<br/>
		Per Page: <%= remote_per_page_select %>
		<% if @search.page_count > 1 %>
			<div class="pages">
				<%= remote_page_links %>
			</div>
		<% end %>
<% else %>
	No listings found.
<% end %>

app/views/listings/_powersubcategories_select.html.erb
<%= select :listing, :subcategory, @powersubcategories, {:size => 10, :prompt => "-Select a Category First-"} %>

app/views/listings/admin.html.erb
<table width="883" border="0" cellpadding="20" cellspacing="0">
	<tr>
		<td align="left" valign="top">
			<% if flash[:notice] %>
      	<div class="notice"><%= flash[:notice] %></div>
	    <% end %>
			<table width="100%" border="0" cellpadding="0" cellspacing="0" id="myListings">
				<tr>
					<td width="25%">
						<%= page_entries_info @listings %>
					</td>
					<td width="75%" align="right" valign="middle">
						<%= will_paginate @listings %>
					</td>
				</tr>
				
				<% if @listings_count > 0 %>
					<% @listings.each do |listing| %>
				
						<tr>
							<td width="15%" align="left">
								<p>
									<% if listing.listingtype == "auto" %>
										<strong><%= listing.year %> <%= listing.make %> <%= listing.model %></strong>
									<% else %>
										<strong><%= listing.year %> <%= listing.make %> <%= listing.category %></strong>
									<% end %>
								</p>
								<p>
									<strong>
										<% if listing.photos.all.count == 0 %>
											<%= image_tag "no-photo-small.jpg", :alt => "No Photo Available", :border => 0 %>
										<% else %>
											<% listing.photos.all(:limit => 1).each do |photo| %>
												<%= image_tag smallphoto_path(photo, :jpg), :alt => photo.name %>
											<% end %>
										<% end %>
									</strong>
									<br />
									<br />
									<span class="formText"><%= link_to "Edit", admin_edit_listing_url(:id => listing.id) %> | <%= link_to "Manage Photos", listing_photos_path(listing) %> | <%= link_to 'Delete', user_listing_path(@user, listing), :confirm => 'Are you sure?', :method => :delete %></span>
								</p>
							</td>
							<td width="85%" align="left" valign="middle">
							
								<% if listing.listingtype == "auto" %>
									<%= render :partial => "mylistings_auto", :locals => { :listing => listing } %>
								<% elsif listing.listingtype == "moto" %>
									<%= render :partial => "mylistings_moto", :locals => { :listing => listing } %>
								<% elsif listing.listingtype == "marine" %>
									<%= render :partial => "mylistings_marine", :locals => { :listing => listing } %>
								<% elsif listing.listingtype == "power" %>
									<%= render :partial => "mylistings_power", :locals => { :listing => listing } %>
								<% end %>
									       	
							</td>
						</tr>
						<tr>
							<td colspan="2">
								<p>
									<br />
									<%= image_tag "listing_divider1.png", :size => "596x11" %>
								</p>
							</td>
						</tr>
	
					<% end %>
					
				<% else %>
					
					<tr>
						<td width="100%">This page allows you to add your vehicle(s) to the site.  Simply click on the "Create A New Listing" button to get started!</td>
					</tr>
					
				<% end %>
				
			</table>	
		</td>
	</tr>
</table>

app/views/listings/index.html.erb
<div id="content">
  <div class="page">
    <div class="rightcontent">
      <div class="ad1"> <img src="/assets/ad1.jpg" width="300" height="125" /> </div>
      <div class="ad2"> <img src="/assets/ad2.jpg" width="300" height="125" /> </div>
      <div class="ad3"> <img src="/assets/ad3.jpg" width="300" height="250" /> </div>
    </div>
    <div class="leftcontent"> <span>My Whips</span>
      <div class="lsitarea">
        <div class="pagination">
          <div class="paging">
            <span class="font">Page 01 of 06</span> <img width="171" height="24" src="/assets/pagination.png">
          </div>


          <div class="short_by">
            <span class="sort font">Sort by:</span>
            <form class="float_left" action="#">
              <select>
                <option>Date Added</option>
                <option>No Availability</option>
              </select>
            </form>
          </div>

          <!--
          <div class="list_map">
            <span class="sort">List</span><img src="/assets/list.png" class="list" width="42" height="17" /> <span class="sort">Map</span>
          </div>
           -->
          <div class="clear"></div>

          <% if flash[:notice] %>
              <div class="notice"><%= flash[:notice] %></div>
          <% end %>
        </div>

        <% unless  @listings.blank?%>
            <% @listings.each do |listing| %>
                <div class="post">
                  <div class="leftpost"> <img class="pos_img" src="/assets/innersmallsliderimage2.png" width="114" height="91" />
                    <div class="middilepost">
                      <div class="inline">
                        <h2>
                          <% if listing.listingtype == "auto" %>
                              <%= listing.year %> <%= listing.make %> <%= listing.model %>
                          <% else %>
                             <%= listing.year %> <%= listing.make %> <%= listing.category %>
                          <% end %>
                        </h2>
                        <span class="mileage">Milage : <%=h listing.mileage %></span> </div>
                      <% if listing.owner.city && listing.owner.state %>
                          <span><%=h listing.owner.city %>, <%=h listing.owner.state %></span> <img src="/assets/bubble.png" width="13" height="15" />
                      <%end%>
                      <p class="description"><%=h listing.desc %></p>
                      <table>
                        <tr>
                          <td><span><%= link_to "Edit", edit_user_listing_path(current_user,listing)%>&nbsp;&nbsp;|</span></td>
                          <td><span><%= link_to "Manage Photos", listing_photos_path(listing)%>&nbsp;&nbsp;|</span></td>
                          <td><span><%= link_to "Delete", user_listing_path(current_user,listing), :method=>:delete%></span></td>
                        </tr>
                      </table>



                    </div>
                  </div>
                  <div class="swap"> <span><sup>$</sup><%=h listing.price %></span> </div>
                  <div class="clear"></div>
                </div>
            <%end%>
        <%end%>

        <div class="paginationextra"> <span>Page 01 of 06</span> <img src="images/pagination.png" width="171" height="24" /> </div>
      </div>
      <div class="clear"></div>
    </div>
  </div>
  <div class="clear"></div>
</div>






















<!--






<table width="883" border="0" cellpadding="20" cellspacing="0">
	<tr>
		<td align="left" valign="top">
			<%# if flash[:notice] %>
      	<div class="notice"><%#= flash[:notice] %></div>
	    <%# end %>
			<table width="100%" border="0" cellpadding="0" cellspacing="0" id="myListings">
				<tr>
					<td width="25%">
						<h3>My Listings
							<br />
							<br />
						</h3>
					</td>
					<td width="75%" align="right" valign="middle">
						<%= link_to image_tag("create_new_listing_button.jpg", :alt => "Create New Listing", :size => "108x32", :border => 0), newmain_url %>
					</td>
				</tr>
				
				<% if @listings_count > 0 %>
					<% @listings.each do |listing| %>
				
						<tr>
							<td width="15%" align="left">
								<p>
									<% if listing.listingtype == "auto" %>
										<strong><%= listing.year %> <%= listing.make %> <%= listing.model %></strong>
									<% else %>
										<strong><%= listing.year %> <%= listing.make %> <%= listing.category %></strong>
									<% end %>
								</p>
								<p>
									<strong>
										<% if listing.photos.all.count == 0 %>
											<%#= image_tag "no-photo-small.jpg", :alt => "No Photo Available", :border => 0 %>
										<% else %>
											<% listing.photos.all(:limit => 1).each do |photo| %>
												<%#= image_tag smallphoto_path(photo, :jpg), :alt => photo.name %>
											<% end %>
										<% end %>
									</strong>
									<br />
									<br />
									<span class="formText"><%= link_to "Edit", edit_user_listing_path(@user, listing) %> | <%= link_to "Manage Photos", listing_photos_path(listing) %> | <%= link_to 'Delete', user_listing_path(@user, listing), :confirm => 'Are you sure?', :method => :delete %></span>
								</p>
							</td>
							<td width="85%" align="left" valign="middle">
							
								<% if listing.listingtype == "auto" %>
									<%#= render :partial => "mylistings_auto", :locals => { :listing => listing } %>
								<% elsif listing.listingtype == "moto" %>
									<%#= render :partial => "mylistings_moto", :locals => { :listing => listing } %>
								<% elsif listing.listingtype == "marine" %>
									<%#= render :partial => "mylistings_marine", :locals => { :listing => listing } %>
								<% elsif listing.listingtype == "power" %>
									<%#= render :partial => "mylistings_power", :locals => { :listing => listing } %>
								<% end %>
									       	
							</td>
						</tr>
						<tr>
							<td colspan="2">
								<p>
									<br />
									<%#= image_tag "listing_divider1.png", :size => "596x11" %>
								</p>
							</td>
						</tr>
	
					<% end %>
					
				<% else %>
					
					<tr>
						<td width="100%">This page allows you to add your vehicle(s) to the site.  Simply click on the "Create A New Listing" button to get started!</td>
					</tr>
					
				<% end %>
				
			</table>	
		</td>
	</tr>
</table>
-->

app/views/listings/searchlistings.html.erb
<% remote_form_for @search, :url => {:action => "searchlistings"} do |f| %>
	<fieldset>
		<legend>Advanced Search</legend>
		
		<% f.fields_for @search.conditions do |listings| %>
			<%= listings.label "Year:" %><br/>
			<%= listings.text_field :year_is %><br/>
			<br/>
			<%= listings.label "Make:" %><br/>
			<%= listings.text_field :make_is %><br/>
			<br/>
			<%= listings.label "Model:" %><br/>
			<%= listings.text_field :model_is %><br/>
			<br/>
			<%= listings.label "Price Less Than:" %><br/>
			<%= listings.text_field :price_lt %><br/>
			<br/>
			<%= f.submit "Search Listings" %>
		<% end %>	
	</fieldset>
<% end %>

<div id="listingsresults">
</div>

app/views/listings/searchmotorcycles.html.erb
<% remote_form_for @search, :url => {:action => "searchmotorcycles"} do |f| %>
	<fieldset>
		<legend>Advanced Search</legend>
		
		<% f.fields_for @search.conditions do |listings| %>
			<%= listings.label "Year:" %><br/>
			<%= listings.text_field :year_is %><br/>
			<br/>
			<%= listings.label "Make:" %><br/>
			<%= listings.text_field :make_is %><br/>
			<br/>
			<%= listings.label "Model:" %><br/>
			<%= listings.text_field :model_is %><br/>
			<br/>
			<%= listings.label "Price Less Than:" %><br/>
			<%= listings.text_field :price_lt %><br/>
			<br/>
			<%= listings.hidden_field :listingtype_is, :value => "motorcycle" %>
			<%= f.submit "Search Motorcycles" %>
		<% end %>	
	</fieldset>
<% end %>

<div id="listingsresults">
</div>