config/routes.rb
SmwSmw::Application.routes.draw do

  root :to => 'home#index'

  get 'home/:id' => 'home#admin'

  get 'admin_edit_listing/:id' => 'listings#admin_edit'

  get 'listings_admin/:id' => 'listings#admin'

  get 'login' => 'user_sessions#new', :as => :login

  get 'logout' => 'user_sessions#destroy', :as => :logout

  get 'searchautos' => 'autolistings#searchautos', :as => :searchautos
  get 'searchmotos' => 'motolistings#searchmotos', :as => :searchmotos
  get 'searchmarine' => 'marinelistings#searchmarine', :as => :searchmarine
  get 'searchpower' => 'powerlistings#searchpower', :as => :searchpower

  get 'about' => 'home#about', :as => :about

  get 'contact' => 'home#contact', :as => :contact

  get 'faq' => 'home#faq', :as => :faq

  get 'whatiwant' => 'whatiwant#whatiwant', :as => :whatiwant

  resources :whatiwant do
    collection do
      get 'get_automodels'
      get 'get_marinesubcategories'
      get 'get_powersubcategories'
    end
  end

  get 'basicsearch' => 'listings#basicsearch', :as => :basicsearch

  get 'newmain' => 'listings#newmain', :as => :newmain

  get 'photos/:id' => 'photos#showlarge', :as => :largephoto

  get 'medphoto/:id' => 'photos#showmedium', :as => :medphoto

  get 'smallphoto/:id' => 'photos#showsmall', :as => :smallphoto

  get 'inbox' => 'messages#inbox', :as => :inbox

  get 'sent' => 'messages#sent', :as => :sent

  resources :messages do
    member do
      delete 'deletesent'
      get 'reply'
      post 'create_reply'
    end
  end

  get 'privacypolicy' => 'home#privacypolicy', :as => :privacypolicy

  get 'visitoragreement' => 'home#visitoragreement', :as => :visitoragreement

   resources :wishlists do
     collection do
       get 'new_auto'
       get 'new_moto'
       get 'new_marine'
       get 'new_power'
     end
   end

   resources :favorites
   resources :users, :has_many=>:listings

   resources :users do
     resources :listings do

     end
   end

   resources :listings do
    resources :photos
   end

   resources :user_sessions

   resources :users, :shallow => true do
    resources :listings, :name_prefix => nil do
      resources :photos
    end
    resources :wishlists
    resources :favorites
  end

   resources :password_resets
   resources :autocategories
   resources :automodels
   resources :marinecategories do
     collection do
       get 'get_marinesubcategories'
     end
   end
   resources :marinemakes
   resources :motocategories
   resources :motomakes
   resources :powercategories do
     collection do
       get 'get_powersubcategories'
     end
   end
   resources :powermakes
   resources :autolistings do
     collection do
       post 'autolistingsresults'
       get 'get_automodels'
       post 'autolistingsresults_new'
       get 'autolistingsresults_new'
     end
   end

   resources :motolistings do
     collection do
       post 'motolistingsresults'
       get 'motolistingsresults'
     end
   end

   resources :marinelistings do
     collection do
       post 'marinelistingsresults'
       get 'marinelistingsresults'
     end
   end

   resources :powerlistings do
     collection do
       post 'powerlistingsresults'
       get 'powerlistingsresults'
     end
   end

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  attr_accessible :user_id, :listing_id
  belongs_to :user
  belongs_to :listing
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # GET /favorites
  # GET /favorites.xml
  def index
  	@user = current_user
  	if @user
	    @favorites = @user.favorites.find(:all, :include => {:listing => :photos})
	  end
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @favorites }
    end
  end

  # GET /favorites/1
  # GET /favorites/1.xml
#  def show
#    @favorite = Favorite.find(params[:id])
#
#    respond_to do |format|
#      format.html # show.html.erb
#      format.xml  { render :xml => @favorite }
#    end
#  end

  # GET /favorites/new
  # GET /favorites/new.xml
  def new
    @favorite = Favorite.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @favorite }
    end
  end

  # POST /favorites
  # POST /favorites.xml
  def create
    @favorite = Favorite.new(params[:favorite])

    respond_to do |format|
      if @favorite.save
        flash[:notice] = 'Favorite was successfully created.'
        format.html { redirect_to :back }
        format.xml  { render :xml => @favorite, :status => :created, :location => @favorite }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @favorite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.xml
  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy

    respond_to do |format|
    	flash[:notice] = 'Favorite was successfully removed.'
      format.html { redirect_to(favorites_path) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/edit.html.erb
<h1>Editing favorite</h1>

<%= form_for(@favorite) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </p>
  <p>
    <%= f.label :listing %><br />
    <%= f.text_field :listing %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<%if current_user%>
    <div id="content">
      <div class="page">
        <div class="rightcontent">
          <div class="ad1"> <img src="/assets/ad1.jpg" width="300" height="125" /> </div>
          <div class="ad2"> <img src="/assets/ad2.jpg" width="300" height="125" /> </div>
          <div class="ad3"> <img src="/assets/ad3.jpg" width="300" height="250" /> </div>
          <div class="ad3"> <img src="images/ad3.jpg" width="300" height="250" /> </div>
          <div class="ad3"> <img src="images/ad3.jpg" width="300" height="250" /> </div>
        </div>
        <div class="leftcontent">

          <div class="lsitarea"> <img width="725" height="276" class="twocolumns p_img" src="images/mainimage.png">

            <h1 class="headingh1">My <strong>Favorites</strong></h1>

            <div class="pagination"> <span class="sort">Sort by:</span>
              <form action="#">
                <select>
                  <option>Select Category</option>
                </select>
              </form>
              <div class="clear"></div>
            </div>
            <%unless @favorites.blank?%>
                <%  @favorites.each do |fav| %>
                    <div class="post">
                      <div class="leftpost">
                        <div class="middilepost">
                          <div class="inline">
                            <h2>
                              <% if fav.listing.listingtype == "auto" %>
                                  <%= fav.listing.min_year %> - <%= fav.listing.max_year %> <%= fav.listing.make %> <%= fav.listing.model %>
                              <% else %>
                                  <%= fav.listing.min_year %> - <%= fav.listing.max_year %> <%= fav.listing.category %>
                              <% end %>
                            </h2>
                            <div class="clear"></div>
                          </div>
                          <p>Transmission: <%=h fav.listing.transmission %> - <%=h fav.listing.max_price %></p>
                          <p>Mileage:  <%=h fav.listing.mileage %></p>
                          <p>Price:  <%=h fav.listing.price %></p>
                          <p>Owner Name:  <%=h fav.listing.owner.username %></p>
                          <p>
                            <!--<a href="#">Modify Item &raquo;</a>-->
                            <%= link_to "Delete Wishlist Item",fav, :confirm => 'Are you sure?', :method=>:delete, :class=>"remove"%>
                          </p>
                        </div>
                      </div>
                      <div class="clear"></div>
                    </div>
                <%end%>
            <%end%>
            <div class="post">
              <div class="">
                <div class="middilepost">
                  <div class="inline">

                    <div class="clear"></div>
                  </div>

                  <span></span>.</div>
              </div>
              <div class="clear"></div>
            </div>
          </div>
          <div class="clear"></div>



        </div>
        <div class="clear"></div>
    </div>

<%else%>
    <div id="content">
      <div class="page">
        <div class="rightcontent">
          <div class="ad1"> <img src="/assets/ad1.jpg" width="300" height="125" /> </div>
          <div class="ad2"> <img src="/assets/ad2.jpg" width="300" height="125" /> </div>
          <div class="ad3"> <img src="/assets/ad3.jpg" width="300" height="250" /> </div>
          <div class="ad3"> <img src="images/ad3.jpg" width="300" height="250" /> </div>
          <div class="ad3"> <img src="images/ad3.jpg" width="300" height="250" /> </div>
        </div>
        <div class="leftcontent">
          <div class="lsitarea">
            <h1 class="headingh1">My <strong>Wishlist</strong></h1>
            <div class="clear"></div>
          </div>
          <!--<div class="post">-->
          <p><%= link_to "Register", new_user_path, {:style=>'color:#649D4A'} %> or <%= link_to "Log in", login_url, {:style=>'color:#649D4A'} %> to set up a "Wishlist".</p>
          <p>A Wishlist will work for you while you're away - enabling our team to help you find a Perfect Swap.</p>
          <!--</div>-->
          <div class="clear"></div>
        </div>
      </div>
      <div class="clear"></div>
    </div>
<%end%>














<% if flash[:notice] %>
	<div class="notice"><%= flash[:notice] %></div>
<% end %>
<% if @user %>
	<table width="100%" border="1" cellpadding="0" cellspacing="0" bordercolor="#823416" class="searchResultsTable">
		<h3>My Favorites</h3>
		<tr>
			<th height="25" align="left"></th>
			<th height="25" align="left">Year</th>
			<th height="25" align="left">Make</th>
			<th height="25" align="left">Model</th>
			<th height="25" align="left">Trans</th>
			<th height="25" align="left">Mileage</th>
			<th height="25" align="left">Price</th>
			<th height="25" align="left"></th>
		</tr>
		<br/>

		<% @favorites.each do |favorite| %>
		<tr>
			<td align="center">
				<% favorite.listing.photos.all(:limit => 1).each do |photo| %>
					<%= link_to image_tag(smallphoto_url(photo, :jpg), :alt => photo.name, :border => 0), listing_path(favorite.listing) %><br/>
				<% end %>
				<%=h favorite.listing.photos.all.count %>
				<% if favorite.listing.photos.all.count == 1 %>
					&nbsp;Photo<br/>
				<% elsif favorite.listing.photos.all.count == 0 %>
					&nbsp;Photos<br/>
				<% else %>
					&nbsp;Photos<br/>
					<%= link_to image_tag("more_photos.png", :alt => "more photos", :size => "74x10", :border => "0"), favorite %>
					</a>
				<% end %>

			</td>
			<td align="center" valign="middle">
				<%=h favorite.listing.year %>
			</td>
			<td align="center" valign="middle">
				<%=h favorite.listing.make %>
			</td>
			<td align="center" valign="middle">
				<%=h favorite.listing.model %>
			</td>
			<td align="center" valign="middle">
				<%=h favorite.listing.transmission %>
			</td>
			<td align="center" valign="middle">
				<%=h favorite.listing.mileage %>
			</td>
			<td align="center" valign="middle">
				<%=h favorite.listing.price %>
			</td>
			<td align="center" valign="middle">
				<%=h favorite.listing.owner.username %>
			</td>
			<td>
				<%= link_to "Remove", favorite, :confirm => 'Are you sure?', :method => :delete %>
		</tr>
		
		<% end %>
		
	</table>
	
	<p>&nbsp;</p>

	<div align="center">
		<a href="http://www.camaroforumz.com" target="_blank">
			<img src="../images/Ads/Camaro-forumAd.jpg" width="382" height="60" alt="camaroforumz.com" border="0" />
		</a>
		<a href="http://www.dpbolvw.net/click-3732474-10518038" target="_blank">
<img src="http://www.awltovhc.com/image-3732474-10518038" width="468" height="60" alt="$100 Mail-in Rebate on Mickey Thompson Tires & Whe" border="0"/></a>
	</div>

	<br />
	
<% else %>

	<table width="883" border="0" cellpadding="10" cellspacing="0">
		<tr>
			<td align="center" valign="top">
				<p><%= link_to "Register", new_user_path %> or <%= link_to "Log in", login_url %> to set up your "Favorites" list - this will help you track the vehicles you like.<br/>
				</p>
			</td>
		</tr>
		<tr align="center">
			<td>
<!--				<a href="http://www.camaroforumz.com" target="_blank">
					<img src="../images/Ads/Camaro-forumAd.jpg" width="382" height="60" alt="camaroforumz.com" border="0" />
				</a>
-->
				<a href="javascript:gotoshow()">
					<img src="../images/banners/MoparNation.jpg" name="slide" border=0 style="filter:blendTrans(duration=3)" width=382 height=60>
				</a>
				<a href="http://www.dpbolvw.net/click-3732474-10518038" target="_blank">
<img src="http://www.awltovhc.com/image-3732474-10518038" width="468" height="60" alt="$100 Mail-in Rebate on Mickey Thompson Tires & Whe" border="0"/></a>
			</td>
		</tr>
	</table>
	
<% end %>

app/views/favorites/new.html.erb
<h1>New favorite</h1>

<%= form_for(@favorite) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </p>
  <p>
    <%= f.label :listing %><br />
    <%= f.text_field :listing %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', favorites_path %>