config/routes.rb
SmwSmw::Application.routes.draw do

  root :to => 'home#index'

  get 'home/:id' => 'home#admin'

  get 'admin_edit_listing/:id' => 'listings#admin_edit'

  get 'listings_admin/:id' => 'listings#admin'

  get 'login' => 'user_sessions#new', :as => :login

  get 'logout' => 'user_sessions#destroy', :as => :logout

  get 'searchautos' => 'autolistings#searchautos', :as => :searchautos
  get 'searchmotos' => 'motolistings#searchmotos', :as => :searchmotos
  get 'searchmarine' => 'marinelistings#searchmarine', :as => :searchmarine
  get 'searchpower' => 'powerlistings#searchpower', :as => :searchpower

  get 'about' => 'home#about', :as => :about

  get 'contact' => 'home#contact', :as => :contact

  get 'faq' => 'home#faq', :as => :faq

  get 'whatiwant' => 'whatiwant#whatiwant', :as => :whatiwant

  resources :whatiwant do
    collection do
      get 'get_automodels'
      get 'get_marinesubcategories'
      get 'get_powersubcategories'
    end
  end

  get 'basicsearch' => 'listings#basicsearch', :as => :basicsearch

  get 'newmain' => 'listings#newmain', :as => :newmain

  get 'photos/:id' => 'photos#showlarge', :as => :largephoto

  get 'medphoto/:id' => 'photos#showmedium', :as => :medphoto

  get 'smallphoto/:id' => 'photos#showsmall', :as => :smallphoto

  get 'inbox' => 'messages#inbox', :as => :inbox

  get 'sent' => 'messages#sent', :as => :sent

  resources :messages do
    member do
      delete 'deletesent'
      get 'reply'
      post 'create_reply'
    end
  end

  get 'privacypolicy' => 'home#privacypolicy', :as => :privacypolicy

  get 'visitoragreement' => 'home#visitoragreement', :as => :visitoragreement

   resources :wishlists do
     collection do
       get 'new_auto'
       get 'new_moto'
       get 'new_marine'
       get 'new_power'
     end
   end

   resources :favorites
   resources :users, :has_many=>:listings

   resources :users do
     resources :listings do

     end
   end

   resources :listings do
    resources :photos
   end

   resources :user_sessions

   resources :users, :shallow => true do
    resources :listings, :name_prefix => nil do
      resources :photos
    end
    resources :wishlists
    resources :favorites
  end

   resources :password_resets
   resources :autocategories
   resources :automodels
   resources :marinecategories do
     collection do
       get 'get_marinesubcategories'
     end
   end
   resources :marinemakes
   resources :motocategories
   resources :motomakes
   resources :powercategories do
     collection do
       get 'get_powersubcategories'
     end
   end
   resources :powermakes
   resources :autolistings do
     collection do
       post 'autolistingsresults'
       get 'get_automodels'
       post 'autolistingsresults_new'
       get 'autolistingsresults_new'
     end
   end

   resources :motolistings do
     collection do
       post 'motolistingsresults'
       get 'motolistingsresults'
     end
   end

   resources :marinelistings do
     collection do
       post 'marinelistingsresults'
       get 'marinelistingsresults'
     end
   end

   resources :powerlistings do
     collection do
       post 'powerlistingsresults'
       get 'powerlistingsresults'
     end
   end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout "application", :except => :index
  def index

    @user = current_user
    @automakes = Automodels.find(:all, :order => 'make ASC', :select => 'distinct make')

    @automodels = params[:make].blank? ? Automodels.all : Automodels.find_all_by_make(params[:make], :order => "model ASC")

    #@automodels = "" #send a blank list when the page is first loaded so it can be replaced by the partial when a Make is selected

    @autocategories = Autocategories.find(:all, :order => 'category ASC')

    @motocategories = Motocategories.find(:all, :order => 'category ASC')
    @motomakes = Motomakes.find(:all, :order => 'sort_order ASC')
    @marinecategories = Marinecategories.find(:all, :order => 'category ASC', :select => 'distinct category')

    #@marinesubcategories = "" #Marinecategories.find(:all, :order => 'subcategory ASC')
    @marinesubcategories = params[:category].blank? ? Marinecategories.find(:all, :order => 'subcategory ASC') : Marinecategories.find_all_by_category(params[:category], :order => "subcategory ASC").map{|m| [m.subcategory, m.subcategory]}
    @marinemakes = Marinemakes.find(:all, :order => 'make ASC')
    @powercategories = Powercategories.find(:all, :order => 'category ASC', :select => 'distinct category')

    #@powersubcategories = "" #Powercategories.find(:all, :order => 'subcategory ASC')

    @powersubcategories = params[:category].blank? ? Powercategories.find(:all, :order => 'subcategory ASC') : Powercategories.find_all_by_category(params[:category], :order => "subcategory ASC").map{|m| [m.subcategory, m.subcategory]}

    @powermakes = Powermakes.find(:all, :order => 'sort_order ASC')
    #@search = Listing.new_search(params[:search]) #TIDO
    #@q = Listing.search_m(params[:q])
    #puts @search.inspect
    #puts "______________________________________"
    #	@listings_count = @search.count

    @featuredauto = Listing.where("featured = ? AND listingtype = ?", true, 'auto').first
    @featuredmoto = Listing.where("featured = ? AND listingtype = ?", true, 'moto').first
    @featuredmarine = Listing.where("featured = ? AND listingtype = ?", true, 'marine').first
    @featuredpower = Listing.where("featured = ? AND listingtype = ?", true, 'power').first
  	
  	#@automakes = Automodels.find(:all, :order => 'make ASC', :select => 'distinct make')
  	#@automodels = ""
  	#@autocategories = Autocategories.all
  	#@search = Listing.new_search(params[:search]) TODO
    @search = Listing.all
    unless @search.blank?
      @listings = @search #TODO
      @listings_count = @search.count #TODO
    end

  	
  	render :action => "index", :layout => "home"
  end

  def faq
  end

  def about
  end

  def contact
  	@message = Message.new
  end
  
  def admin
  	@user = current_user
  	if @user
  		if @user.admin
  			render
  		else
  			flash[:notice] = 'Restricted Page'
  			redirect_to(root_url)
  		end
  	else
  		flash[:notice] = 'Restricted Page'
 			redirect_to(root_url)
 		end
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<div class="clear"></div>
<div id="footer">
  <div class="page">
    <div class="footerpart">
      <ul>
        <h2>My Whip</h2>
        <li><%= link_to "My Account", login_path %></li>
        <li><%= link_to("My Listings", listings_url) %></li>
        <li><%= link_to("My Favorites", favorites_path) %></li>
      </ul>
    </div>
    <div class="footerpart">
      <ul>
        <h2>Support & Help</h2>
        <li><%= link_to("FAQ", faq_url) %></li>
        <li><a href="#">Support</a></li>
        <li><%= link_to("Contact Us", contact_url) %></li>
      </ul>
    </div>
    <div class="footerpart">
      <ul>
        <h2>Legal</h2>
        <li><%= link_to("Privacy Policy", privacypolicy_url) %></li>
        <li><%= link_to("Terms of Use", visitoragreement_url) %></li>
      </ul>
    </div>
    <div class="footerpart last">
    </div>
    <div class="clear"></div>
  </div>
  <div class="clear"></div>
</div>
<div class="clear"></div>
<div id="downfooter">
  <div class="page">
    <p class="leftp"> &copy; 2013 Swapmywhip.com, Inc. All Rights Reserved. <br />
      "Swapmywhip.com" is a registered trademark of Krause Capital, LLC used under exclusive license </p>
    <ul>
      <li><a href="#">Privacy policy</a></li>
      <li><a href="#">Terms Of Use</a></li>
      <li class="last"><a href="#">Contact Us</a></li>
    </ul>
    <div class="clear"></div>
  </div>
</div>

app/views/home/_header.html.erb
<div id="header">
  <div class="page">
    <div class="logo"> <img src="/assets/logo.png" width="177" height="87" class="logo"/> <img src="/assets/headerlogotext.png" width="435" height="29" class="logotext" /> </div>
    <div class="social">
      <ul>
        <li><a href="#"><img src="/assets/facebook.png" width="57" height="31"  /></a></li>
        <li><a href="#"><img src="/assets/twitter.png" width="57" height="31"  /></a></li>
      </ul>
      <div class="login_p">
        <% if current_user %>
            <%= link_to "Inbox", inbox_path %> <%= link_to "("+ unread_messages.to_s + ")", inbox_path %> |
            <%= link_to "Sent", sent_path %> |
            <%= link_to "Edit Profile", edit_user_path(:current) %> |
            <%= link_to "Logout", logout_path %>
        <% else %>
            <%= link_to "Register", new_user_path%> |
            <%= link_to "Login", login_path %>
        <% end %>
      </div>
    </div>

    <div class="clear"></div>


    <div id="toplinks">
      <div class="rg_head_top_div">

        <%= render :partial => 'menu'%>

      </div>
      <div class="clear"></div>
      <script type="text/javascript">
          var MenuBar1 = new Spry.Widget.MenuBar("MenuBar1", {imgDown:"SpryAssets/SpryMenuBarDownHover.gif", imgRight:"SpryAssets/SpryMenuBarRightHover.gif"});
      </script>
    </div>
  </div>
</div>

app/views/home/_home_page_content.html.erb
<div id="content" class="mrg_tp">
  <div class="page">
    <div class="leftcontent">
      <div class="uppercontent margin_tp"> <span>Welcome to</span><span class="boldclass"> Swapmywhip.com</span>
        <p>Tired of the old way of finding a new ride?  Without cash, you have to sell your current ride first, or take a hit in the wallet when you trade it in. There's a better way...</p>
        <p>We created a website where YOU can get a better deal. <span class="smwText">SwapMyWhip.com</span> lets you swap your vehicle with other private owners (or just purchase outright). Whether you're upsizing, downsizing, found a new hobby, or just enjoy something new every year, this site has something for you.</p>
        <p>Swap as often as you'd like, because you'll get value when you swap!
          Whatever your situation, you'll find that swapping for your next vehicle is the way to go!</p>
        <p>SwapMyWhip.com is free to use, so register today!</p>
        <div class="clear"></div>
      </div>
      <div class="java"> <span>Find A</span><span class="boldclass"> Whip</span>

        <!--lightbox-->
        <style type="text/css">

            .overlay {
                background: url("/assets/magnifier.png") no-repeat scroll center 105px transparent;
                height: 199px;
                position: absolute;
                width: 351px;
                z-ind/ex: 9999;
                opacity:0;
            }

            .overlay h5 {
                display: block;
                font-family: Oswald;
                font-size: 49px;
                font-weight: bold;
                line-height: 125px;
                margin: 0;
                text-align: center;
            }
            .overlay:hover
            {
                opacity:1;
                background-color:rgba(0,0,0,.5)
            }
        </style>
        <div class="lightbox">
          <a class="fancybox" rel="group" href="autolistings/autolistingsresults_new?listing_type=auto">
            <div class="overlay">
              <h5>AUTOMOTIVE</h5>
            </div>
          <img src="/assets/lightbox1.jpg" alt="" />
          </a>
          <a class="fancybox" rel="group" href="marinelistings/marinelistingsresults?listing_type=marine">
          <div class="overlay">
            <h5>MARINE</h5>
          </div>
          <img src="/assets/lightbox2.jpg" alt="" />
          </a>
          <a class="fancybox" rel="group" href="motolistings/motolistingsresults?listing_type=moto">
          <div class="overlay">
            <h5>MOTORCYCLE</h5>
          </div>
          <img src="/assets/lightbox3.jpg" alt="" />
          </a>
          <a class="fancybox" rel="group" href="powerlistings/powerlistingsresults?listing_type=power">
          <div class="overlay">
            <h5>POWER SPORTS</h5>
          </div>
          <img src="/assets/lightbox4.jpg" alt="" />
          </a>
        </div>

        <!--lightbox-->
      </div>
    </div>
    <div class="rightcontent">
      <div class="ad1"> <img src="/assets/ad1.jpg" width="300" height="125" /> </div>
      <div class="ad2"> <img src="/assets/ad2.jpg" width="300" height="125" /> </div>
      <div class="ad3"> <img src="/assets/ad3.jpg" width="300" height="250" /> </div>
      <div class="ad3"> <img src="/assets/ad3.jpg" width="300" height="250" /> </div>
    </div>
    <div class="clear"></div>
  </div>
</div>

app/views/home/_menu.html.erb
<!--NAVIGATION START-->
<nav>

  <div id='cssmenu'>
    <ul>
      <li><%= link_to 'Home', root_url%></li>
      <li class='active has-sub'><a href='#'><span>Find A Whip</span></a>
        <ul>
          <li class='has-sub'>
            <%= link_to "Automobiles", autolistingsresults_new_autolistings_path(:listing_type => 'auto')%>
          </li>
          <li class='has-sub'>
            <%= link_to "Motorcycles", motolistingsresults_motolistings_path(:listing_type => 'moto') %>
          </li>
          <li class='has-sub'>
            <%= link_to "Marine", marinelistingsresults_marinelistings_path(:listing_type => 'marine') %>
          </li>
          <li class='has-sub'>
            <%= link_to "Powersports", powerlistingsresults_powerlistings_path(:listing_type => 'power')%>
          </li>
        </ul>
      </li>
      <li><%= link_to("Wishlist", wishlists_url) %></li>
      <li><%= link_to("My Whip", listings_url) %></li>
      <li><%= link_to("Favorites", favorites_path) %></li>
      <li><%= link_to("About Us", about_url) %></li>
      <li><%= link_to("How it Works", faq_url) %></li>
      <li class='last'><%= link_to("Contact Us", contact_url) %></li>
    </ul>
  </div>

</nav>
<!--NAVIGATION ENTER-->

app/views/home/about.html.erb
<div id="content">
  <div class="page"> <img class="p_img" src="/assets/fullwidth.jpg" width="1050" />
    <div class="leftcontent">
      <div class="uppercontent"> <span>About Us</span>
        <p>The idea for <span class="smwText">SwapMyWhip.com</span> came to me out of pure frustration. I was in search of an alternative to the traditional methods of selling and buying vehicles. Buying a new car was always fun and exciting, but selling a car - ugh....I always dreaded that part of the process.
        </p>
        <p>I'd noticed ads on occasion for vehicle owners wishing to trade, but never found a site that was well organized and devoted to trading. And, working with dealerships and dealer websites - well, I never felt that I was getting good value for my trade in.
        </p>
        <p>So, the concept was born......
        </p>
        <p>I set out to put together a team of professionals - from programmers to graphic artists, and we collaborated on the project for the better part of a year, to ensure that every detail was perfect.
        </p>
        <p>An enormous amount of time, energy and thoughtful design went into making <span class="smwText">Swap My Whip</span> a reality. We believe we've created the greatest system ever, to help you find a new ride,  and create a new home for your old one. At <span class="smwText">Swap My Whip</span>, we are obsessed with ensuring that every customer finds his or her right swap. From day one, our focus has been to offer our customers the opportunity to realize high value for their vehicle, in an environment that has never before offered it.
        </p>
        <p>This site has been designed to promote a sense of community to its users, with the hope that honesty and fairness will play a key role in all the transactions that transpire here. Please check us out - we think you'll love <span class="smwText">Swap My Whip</span> so much that you'll want to spread the word.
        </p>
        <p>
          <span class="greenText">Welcome! Now, go &quot;Get your Swap On!&quot; </span>
          <br />
        </p>
        <p><b>Daniel Krause</b></p>
        <div class="clear"></div>
      </div>
    </div>
    <div class="clear"></div>
  </div>
</div>

app/views/home/admin.html.erb
<table width="883" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td align="left" valign="top">
			<h2>Please select the object you wish to view/edit</h2>
			<p><%= link_to "Auto Categories", autocategories_path %></p>
			<p><%= link_to "Auto Makes/Models", automodels_path %></p>
			<p><%= link_to "Marine Categories", marinecategories_path %></p>
			<p><%= link_to "Marine Makes", marinemakes_path %></p>
			<p><%= link_to "Moto Categories", motocategories_path %></p>
			<p><%= link_to "Moto Makes", motomakes_path %></p>
			<p><%= link_to "Power Categories", powercategories_path %></p>
			<p><%= link_to "Power Makes", powermakes_path %></p>
			<p><%= link_to "Listings", listings_admin_url %></p>
		</td>
	</tr>
</table>

app/views/home/contact.html.erb
<div id="content">
  <div class="page"> <img class="p_img" src="/assets/fullwidth.jpg" width="1050" />
    <div class="leftcontent">
      <div class="uppercontent"> <span>Contact</span><span class="boldclass"> Us</span>
        <p>Like what you see? Have a question or comment? Like to advertise? Shoot us a quick message.</p>
        <div>
          <!-- panel -->

          <!-- panel -->
        </div>
        <div class="clear"></div>
      </div>
    </div>
    <div class="clear"></div>
    <div class="contactwidget">
      <% if flash[:notice] %>
          <div class="notice"><%= flash[:notice] %></div>
      <% end %>
      <%= form_for @message, :url => {:controller => "messages", :action => "create"} do |f| %>
          <% if @message.errors.any? %>
              <div id="errorExplanation">
                <h2><%= pluralize(@message.errors.count, "error") %> prohibited this post from being saved:</h2>

                <ul>
                  <% @message.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>
          <%= f.hidden_field :recipient_id, :value => 1 %>
      <form action="#">
        <div class="username">
          <label>Name*</label>
          <%= f.text_field :name, :size => 35, :tabindex => 1 %>
        </div>
        <div class="youremail">
          <label>your email*</label>
          <%= f.text_field :email, :size => 35, :tabindex => 2 %>
        </div>
        <div class="phoneno">
          <label>phone</label>
          <%= f.text_field :phone, :size => 35, :tabindex => 3 %>
        </div>
        <div class="subject">
          <label>subject*</label>
          <%= f.text_field :subject, :size => 35, :tabindex => 3 %>
        </div>
        <div class="message">
          <label>message*</label>
          <%= f.text_area :body, :cols => 32, :rows => 10, :tabindex => 4 %>
        </div>
        <%= image_submit_tag "sendbutton.jpg", :alt => "submit", :size => "54x25", :border => 0 %>
      <%end%>
    </div>
    <div class="rightwidget"> <span>Swap My Whip </span><span class="boldclass">Direct Contacts</span>
      <p>To email us directly, feel free to use the following contacts.</p>
      <div class="info"> <span>General : </span>
        <p>info@swapmywhip.com</p>
        <span>Social Media : </span>
        <p>socialmedia@swapmywhip.com</p>
        <span>Facebook : </span>
        <p>https://www.facebook.com/Swap-My-Whip</p>
        <span>Twitter : </span>
        <p>https://twitter.com/SwapMyWhip</p>
      </div>
    </div>
    <%#= link_to image_tag("468x60_imgad.jpg", :alt => "AIM Mobile Inspections", :border => 0), "http://www.aimmobileinspections.com/SwapMyWhip-car-inspections.php", :popup => true %>
  </div>
</div>
</div>

app/views/home/forums.html.erb
<table width="883" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td align="center" valign="top">
			<p>Forums coming soon!</p>
			<p>
				Anyone wishing to moderate a forum for the following vehicles, please drop us an email @ <a href="mailto:info@swapmywhip.com">info@swapmywhip.com</a>:
				<br />
				Mustangs, Corvettes, Mopar, Camaros, Harley Davidson, Moto Guzzi, Porsche, Audi, VW, BMW Cars, BMW Motorcycles, Triumph Motorcycles, Victory Motorcycles
			</p>
		</td>
	</tr>
</table>

app/views/home/index.html.erb
<table width="883" border="0" cellpadding="0" cellspacing="0">
	<% if flash[:notice] %>
		<div class="notice"><%= flash[:notice] %></div>
	<% end %>
	<tr><br />
		<td align="center" valign="top">

			<div class="leftColumn">
				<p>
					<span style="font-weight: bold;">
						<strong>Ready to list your vehicle,<br />
										or contact an owner about<br />
										purchasing outright?
						</strong>
					</span>
					<br />
					<%= link_to "Register now", new_user_path, :style => "color:  #394a59;" %> and get started.
				</p>
				<p>
					<span>
						<strong>Just want to check us out?</strong>
					</span>
					<br />
					Click below under &quot;Quick Search.&quot;
				</p>
				<p>
					<%= link_to "How Our Site Works", faq_url, :style => "color:  #394a59; font-size: 12px; font-weight: bold;" %>
				</p>
				<p>
					<br />
					<span style="font-size: 17px; font-weight: bold;">Quick Search<br />for Whips</span>
					<br />
					See what was listed today.
				</p>
				<p>
					<%= link_to "Automobiles", autolistingsresults_new_autolistings_path(:listing_type => 'auto'), :style => "font-weight: bold; color: #394a59;" %>
				</p>
				<p>
					<%= link_to "Motorcycles", motolistingsresults_motolistings_path(:listing_type => 'moto'), :style => "font-weight: bold; color: #394a59;" %>
				</p>
				<p>
					<%= link_to "Marine", marinelistingsresults_marinelistings_path(:listing_type => 'marine'), :style => "font-weight: bold; color: #394a59;" %>
				</p>
				<p>
					<%= link_to "Powersports", powerlistingsresults_powerlistings_path(:listing_type => 'power'), :style => "font-weight: bold; color: #394a59;" %>
				</p>
			</div>

			<div class="centerColumn">
				<center>
					<h2>
						<strong style="font-size: 1.4em;">The Vehicle Trading Marketplace</strong>
					</h2>
				</center>
				<span style="font-size: 1.2em; text-align: left; color: #000;">
					<p>
						Tired of the old way of finding a new ride?  Without cash, you have to sell your current ride first, or take a hit in the wallet when you trade it in. There's a better way...
					</p>
					<p>
						We created a website where YOU can get a better deal. <span class="smwText">SwapMyWhip.com</span> lets you swap your vehicle with other private owners (or just purchase outright). Whether you're upsizing, downsizing, found a new hobby, or just enjoy something new every year, this site has something for you.
					</p>
					<p>
						Swap as often as you'd like, because you'll get value when you swap!
Whatever your situation, you'll find that swapping for your next vehicle is the way to go!
					</p>
					<p>
						SwapMyWhip.com is free to use, so register today!
					</p>
				</span>
<!--				<p align="center">
					<a href="http://www.youtube.com/watch?v=xBq9FA_Z5Zg" target="_blank" style="font-size:16px; font-weight:bold; color:#823416;">
						Check out our YouTube video!
					</a>
				</p>
-->
				<p style="text-align: center">
					<span class="greenText">Ready, Set, Swap! Click a category below.</span>
				</p>
				<div id="socialNav">
          <a href="https://www.facebook.com/pages/Swap-My-Whip/117420464960200?ref=ts" title="Swap My Whip Facebook Page" class="facebook"></a>
          <a href="https://twitter.com/#!/SwapMyWhip" title="Follow us on Twitter" class="twitter"></a>
        </div>
			</div>
			
			<div class="rightColumn">
				<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="250" height="120" id="FlashID" title="free listing ad">
					<param name="movie" value="../flash/free_listing.swf" />
					<param name="quality" value="high" />
					<param name="wmode" value="opaque" />
					<param name="swfversion" value="6.0.65.0" />
				<!-- This param tag prompts users with Flash Player 6.0 r65 and higher to download the latest version of Flash Player. Delete it if you don’t want users to see the prompt. -->
					<param name="expressinstall" value="../Scripts/expressInstall.swf" />
				<!-- Next object tag is for non-IE browsers. So hide it from IE using IECC. -->
				<!--[if !IE]>-->
					<object type="application/x-shockwave-flash" data="../flash/free_listing.swf" width="250" height="120">
					<!--<![endif]-->
						<param name="quality" value="high" />
						<param name="wmode" value="opaque" />
						<param name="swfversion" value="6.0.65.0" />
						<param name="expressinstall" value="../Scripts/expressInstall.swf" />
					<!-- The browser displays the following alternative content for users with Flash Player 6.0 and older. -->
						<div>
							<h4>Content on this page requires a newer version of Adobe Flash Player.</h4>
								<p>
									<a href="http://www.adobe.com/go/getflashplayer">
										<img src="http://www.adobe.com//assets/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player" width="112" height="33" />
									</a>
								</p>
						</div>
					<!--[if !IE]>-->
					</object>
				<!--<![endif]-->
				</object>

				<table cellspacing="0">
					<tr>
						<td>
							<a href="http://www.hubcapandwheelworld.com" target="_blank">
								<img src="..//assets/banners/HubCap_Annie_Banner_250.jpg" border=0 width=250 height=52 alt="HubCap Annie">
							</a>
							<%= link_to image_tag("Abundant-Grounds.png", :border => 0), "http://www.facebook.com/pages/Swap-My-Whip/117420464960200", :popup => true, :alt => "Cars and Coffee" %>
<!--							<%= link_to image_tag("LostMtn-Cruise-in-banner.jpg", :border => 0), "http://www.facebook.com/pages/Swap-My-Whip/117420464960200", :popup => true, :alt => "Lostmtn cruise-in banner" %>
-->
						</td>
					</tr>
				</table>
			</div>
		</td>
	</tr>
</table>

app/views/home/whatitsworth.html.erb
<table width="883" border="0" cellpadding="20" cellspacing="0">
	<tr>
		<td align="left" valign="top">
			<p><strong><span class="smwText">Swap My Whip</span></strong> was founded on the principle of offering it's customers a value oriented method of vehicle exchange. The following websites have proven to be excellent sources for pricing and product reviews. If you find another site that you believe to be a great resource for vehicle values and reviews, please email us, and we'll list it here for everyone's benefit. Please use common sense, and do your due diligence - check prices on similar vehicles for sale using other sources, to determine "What it's worth".
			</p>
			<p>&nbsp;</p>
      <p>&nbsp;</p>
     	<table border="0" cellpadding="10" cellspacing="0">
     		<tr>
     			<td align="center">
			      <%= link_to image_tag("nadaguideslink.jpg", :alt => "new & used car prices, values, ratings & buying guides", :size => "175x107", :border => 0), "http://www.nadaguides.com/home.aspx?l=1&w=28&p=0&f=5000&custID=11161", :popup => true %>
	      		<br/>
			  	  <font face="Arial" size="2">
			  	  	<strong>New & Used Car Prices
					  	  <br />
					  	  at NADAguides.com
					  	</strong>
					  </font>
			    </td>
			    <td align="center">
     	      <%= link_to image_tag("kelleybluebooklink.gif", :alt => "Kelley Blue Book", :size => "207x65", :border => 0), "http://kbb.com", :popup => true %>
			    </td>
			  </tr>
			</table>
		</td>
    <td width="40%" align="right" valign="top">
    	<%= image_tag "atv_boat.png", :size => "253x330", :alt => "atv and boat", :border => 0 %>
    </td>
	</tr>
</table>